using System;
using System.Collections.Generic;
using RecompOne.Runtime;
using RecompOne.Runtime.Context;
using RecompOne.Runtime.Dispatch;
using RecompOne.Runtime.Memory;

namespace Recompiled;

/// <summary>
/// Gives each code overlay a fixed load address.
///
/// Spider-Man's overlays are relocatable. `LoadOverlay` (0x8001B990) looks up
/// `&lt;name&gt;.bin` in CD.WAD, asks the game's heap for a block, reads the image into
/// it, then walks `&lt;name&gt;.rel` patching the image for wherever it happened to land.
/// A static recompile cannot follow that: the recompiled code for an overlay is
/// emitted at fixed addresses, so the image has to be at those addresses too.
///
/// So the allocation is redirected. Every overlay gets a base of its own above the
/// 2 MB the game's allocator knows about (tools/overlays.py assigns them, and the
/// same manifest is baked into the table below), which means the 30 overlays never
/// collide with each other or with a real allocation, and the game's own relocator
/// then produces exactly the image the recompiler was built from.
///
/// The cost is that an overlay image is never reclaimed. That is fine here: each one
/// owns its region permanently, so there is nothing to reclaim it for. Freeing one
/// would be worse than leaking it -- the pointer has no heap block header in front of
/// it, so handing it to the allocator's free list would corrupt the heap. HeapFree
/// therefore ignores anything in the region.
/// </summary>
public static class OverlayPatches
{
    public const uint RegionLo = 0x80200000;
    public const uint RegionHi = 0x802A0000;

    /// <summary>Generated by tools/overlays.py; see config/overlays/manifest.json.</summary>
    static readonly Dictionary<string, uint> Bases = new(StringComparer.OrdinalIgnoreCase)
    {
        ["blackcat"] = 0x80200000, ["carnage"] = 0x80202000, ["chopper"] = 0x8020A000,
        ["cop"] = 0x80211000, ["docock"] = 0x8021B000, ["hostage"] = 0x80221000,
        ["jonah"] = 0x80222000, ["l2a1lsc"] = 0x80225000, ["l5a5lsc"] = 0x80226000,
        ["l5a6lsc"] = 0x80227000, ["l5a7lsc"] = 0x80228000, ["l6a1lsc"] = 0x80229000,
        ["l6a2lsc"] = 0x8022A000, ["l6a3lsc"] = 0x8022B000, ["lizard"] = 0x8022C000,
        ["lizman"] = 0x8022D000, ["mj"] = 0x80236000, ["mysterio"] = 0x80237000,
        ["rhino"] = 0x8023F000, ["scorpion"] = 0x80245000, ["shell"] = 0x8024E000,
        ["simby"] = 0x8026A000, ["spclone"] = 0x80279000, ["submarin"] = 0x8027B000,
        ["superock"] = 0x8027C000, ["thug"] = 0x80282000, ["torch"] = 0x8028E000,
        ["training"] = 0x80290000, ["turret"] = 0x80291000, ["venom"] = 0x80293000,
    };

    // Armed by the CdWadFind for "<name>.bin" and consumed by the allocation that
    // immediately follows it in LoadOverlay. The size is carried across as well: the
    // allocation the game makes for an overlay is for exactly the size CdWadFind just
    // returned, so requiring them to match means a stray lookup that never allocates
    // cannot leak this state onto some unrelated allocation later.
    static string _pendingName;
    static uint _pendingSize;
    static uint _allocSize;

    public static int Redirected { get; private set; }

    /// <summary>True when this name is one of the game's code overlays.</summary>
    public static bool Knows(string name) => name != null && Bases.ContainsKey(name);

    static string ReadCString(IMemory m, uint addr, int max = 64)
    {
        var sb = new System.Text.StringBuilder();
        for (int i = 0; i < max; i++)
        {
            byte b = m.ReadU8(addr + (uint)i);
            if (b == 0) break;
            sb.Append((char)b);
        }
        return sb.ToString();
    }

    /// <summary>Every archive lookup, in order -- set SPIDEY_TRACE_WAD.</summary>
    public static readonly bool TraceWad =
        string.IsNullOrEmpty(System.Environment.GetEnvironmentVariable("SPIDEY_QUIET"));

    static string _lastLookup;
    static uint _lastRa;

    /// <summary>pre-hook on CdWadFind(char *name)</summary>
    public static void CdWadFind(CpuContext c, IMemory m)
    {
        _pendingName = null;
        string name = ReadCString(m, c.A0);
        // Before anything else: a level prefix may be redirected to boot straight into
        // some other level, which repoints a0 at the rewritten name.
        name = LevelSwitch.Redirect(c, m, name);
        _lastLookup = name;
        _lastRa = c.RA;
        if (name.Length > 4 && name.EndsWith(".bin", StringComparison.OrdinalIgnoreCase))
        {
            string key = name.Substring(0, name.Length - 4);
            if (Bases.ContainsKey(key)) _pendingName = key;
        }
    }

    /// <summary>post-hook on CdWadFind -- v0 is the sector-rounded size.</summary>
    public static void CdWadFindExit(CpuContext c, IMemory m)
    {
        Capture.NoteWadLoad(_lastLookup, System.Threading.Interlocked.Read(ref Diag.Frame));
        Replay.NoteWadLoad(_lastLookup, System.Threading.Interlocked.Read(ref Diag.Frame));
        if (TraceWad)
            System.Console.WriteLine($"[wad] {_lastLookup,-16} <- ra=0x{_lastRa:X8}  {(c.V0 == 0 ? "NOT FOUND" : c.V0 + " bytes")}");
        if (_pendingName != null) _pendingSize = c.V0;
    }

    /// <summary>
    /// pre-hook on HeapAlloc(size, heap, flag). Returning false skips the allocator
    /// entirely and leaves v0 as the answer.
    ///
    /// The overlay's block must not come from the game's heap at all. Letting the
    /// allocator run and then overwriting the pointer it returned leaks the whole
    /// block -- the game only ever frees the fixed address it was handed, which is not
    /// a heap block -- and an overlay is tens of kilobytes. A few level loads of that
    /// exhausted the heap, and Spider-Man's response to a failed allocation is to
    /// clear the screen and spin forever at 0x80064F98, which looks exactly like a
    /// hang on the loading screen.
    /// </summary>
    public static bool HeapAlloc(CpuContext c, IMemory m)
    {
        _allocSize = c.A0;
        if (_pendingName == null || _allocSize != _pendingSize) return true;

        uint fixedBase = Bases[_pendingName];
        Log.Sdk($"overlay '{_pendingName}': {_allocSize} bytes served from 0x{fixedBase:X8} " +
                "instead of the heap");
        c.V0 = fixedBase;

        // Activate the overlay's function table. The dispatcher normally does this
        // when the game reads the overlay's LBA off the disc, but these overlays live
        // inside CD.WAD and are read as a byte range of one big file, so that never
        // fires. Doing it here ties activation to the actual load. Regions never
        // overlap, so nothing is evicted and repeat loads are harmless.
        Dispatcher.Load(_pendingName);

        _pendingName = null;
        Redirected++;
        return false;
    }

    /// <summary>
    /// pre-hook on HeapFree(void *p) -- returning false skips the function.
    /// </summary>
    public static bool HeapFree(CpuContext c, IMemory m)
        => !(c.A0 >= RegionLo && c.A0 < RegionHi);
}
