#!/usr/bin/env python3
"""Build SM2-native Bag-Man and Peter Parker from their dedicated DC actors.

Unlike ordinary SM2 skins, slots 13 and 17 change the retail actor's topology and
UV state at runtime.  An un-morphed retail GLB is therefore not a valid transfer
source. These slots use the matching Dreamcast geometry and texture set together,
then name-match and reorder those meshes onto SM2's complete native object table,
hierarchy, and animation metadata. Unlike the generic Spider-Man actor, these
dedicated Dreamcast costumes do not contain web-wing geometry, so none is
fabricated or injected.
"""

from __future__ import annotations

import argparse
import hashlib
import importlib.util
import json
from pathlib import Path
import shutil
import struct
import sys


ROOT = Path(__file__).resolve().parents[2]
CONVERTER = ROOT / "spiderman" / "tools" / "port_dc_character.py"
DEFAULT_OUTPUT = ROOT / "dreamcast" / "converted" / "sm2-spider-man-runtime"
DEFAULT_DONOR = ROOT / "spiderman2" / "extracted" / "wad" / "spidey.psx"
SPECIALS = (
    (13, "SPBAGMAN"),
    (17, "SPPARK"),
)
TEXTURE_SCALE = 4
FNV_OFFSET = 1469598103934665603
FNV_PRIME = 1099511628211
MAGENTA_555 = 0x7C1F


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--dc-models", type=Path, default=ROOT / "dreamcast" / "extracted")
    parser.add_argument(
        "--dc-textures",
        type=Path,
        default=ROOT / "dreamcast" / "decoded" / "textures",
    )
    parser.add_argument("--sm2-donor", type=Path, default=DEFAULT_DONOR)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    return parser.parse_args()


def load_converter():
    spec = importlib.util.spec_from_file_location("dc_character_special_sm2", CONVERTER)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"cannot load converter at {CONVERTER}")
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


def digest(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def fnv1a64(data: bytes) -> int:
    value = FNV_OFFSET
    for byte in data:
        value = ((value ^ byte) * FNV_PRIME) & 0xFFFFFFFFFFFFFFFF
    return value


def replacement_key(
    width: int,
    height: int,
    palette: tuple[int, ...],
    payload: bytes,
) -> str:
    """Return the host replacement key generated by the native PS1 upload."""
    if width & 1 or len(payload) < width * height:
        raise ValueError(f"replacement key requires an even {width}x{height} page")
    indices = payload[: width * height]
    index_hash = fnv1a64(struct.pack("<BHH", 8, width, height) + indices)
    clut_bytes = bytearray()
    for index in sorted(set(indices)):
        color = palette[index]
        runtime_color = 0 if color == MAGENTA_555 else color | 0x8000
        clut_bytes.extend((index, runtime_color & 0xFF, runtime_color >> 8))
    clut_hash = fnv1a64(bytes(clut_bytes))
    return f"{index_hash:016x}_{clut_hash:016x}"


def main() -> None:
    args = parse_args()
    converter = load_converter()
    donor_path = args.sm2_donor.resolve()
    donor = converter.parse_skeleton_donor(donor_path)
    output = args.output.resolve()
    output.mkdir(parents=True, exist_ok=True)
    pack_root = output / "packs" / "dreamcast-sm2-special-costumes"
    pack_texture_root = pack_root / "textures"
    pack_texture_root.mkdir(parents=True, exist_ok=True)
    for stale in pack_texture_root.glob("*.png"):
        stale.unlink()
    host_entries = []
    host_sources: dict[str, str] = {}
    results = []

    for slot, stem in SPECIALS:
        source = args.dc_models.resolve() / f"{stem}.PSX"
        texture_root = args.dc_textures.resolve() / stem
        model = converter.parse_model(source)
        if set(model.mesh_names) != set(donor.mesh_names):
            raise ValueError(f"{stem} and SM2 donor have different mesh-name sets")
        actor = converter.build_character(
            model,
            texture_root,
            TEXTURE_SCALE,
            None,
            skeleton_donor=donor,
        )
        textures = converter.build_texture_library(
            model,
            texture_root,
            TEXTURE_SCALE,
            with_wings=False,
        )
        actor_path = output / f"spidey-slot{slot:02d}.psx"
        texture_path = output / f"sp_tex{slot:02d}-dc.psx"
        actor_path.write_bytes(actor)
        texture_path.write_bytes(textures)

        dimensions = converter.scaled_dimensions(model, TEXTURE_SCALE, False)
        actor_assets = converter.quantize_actor_textures(
            model,
            texture_root,
            dimensions,
        )
        for texture in model.textures:
            source_png = converter.find_texture_png(texture_root, texture)
            width, height = dimensions[texture.index]
            palette, payload = actor_assets[texture.index]
            key = replacement_key(width, height, palette, payload)
            source_sha256 = hashlib.sha256(source_png.read_bytes()).hexdigest()
            previous = host_sources.get(key)
            if previous is not None and previous != source_sha256:
                raise ValueError(f"host texture key collision for {key}")
            host_sources[key] = source_sha256
            destination = pack_texture_root / f"{key}.png"
            if not destination.is_file():
                shutil.copy2(source_png, destination)
            host_entries.append(
                {
                    "slot": slot,
                    "actor": stem,
                    "textureIndex": texture.index,
                    "source": str(source_png),
                    "compatibilitySize": [width, height],
                    "hostSize": [texture.width, texture.height],
                    "runtimeKey": key,
                    "output": str(destination),
                    "sha256": source_sha256,
                }
            )
        results.append(
            {
                "slot": slot,
                "dreamcastSource": str(source),
                "skeletonDonor": str(donor_path),
                "metadata": "SM2 object table, hierarchy, and animation metadata",
                "wingGeometry": "preserved dedicated DC actor; no generic wing injection",
                "textureScale": TEXTURE_SCALE,
                "textureScalePurpose": "compact emulated-VRAM identity only",
                "actor": str(actor_path),
                "actorBytes": len(actor),
                "actorSha256": digest(actor),
                "textureLibrary": str(texture_path),
                "textureBytes": len(textures),
                "textureSha256": digest(textures),
                "meshCount": model.mesh_count,
                "sourceTextureCount": len(model.texture_hashes),
                "withSm2Wings": False,
            }
        )
        print(
            f"built slot {slot:02d} from {stem}: "
            f"{len(actor):,}-byte actor, {len(textures):,}-byte DC texture library"
        )

    (pack_root / "pack.json").write_text(
        json.dumps(
            {
                "formatVersion": 1,
                "id": "dreamcast-sm2-special-costumes",
                "name": "Dreamcast SM2 Special Costume Textures",
                "version": "1",
                "description": (
                    "Original-resolution Dreamcast Bag-Man and Peter Parker textures; "
                    "compact PS1 uploads remain identifiers only."
                ),
                "priority": 100,
                "game": {"id": "SLUS-01378", "strict": True},
            },
            indent=2,
        )
        + "\n",
        encoding="utf-8",
    )
    (pack_root / "texture-manifest.json").write_text(
        json.dumps(
            {
                "schemaVersion": 1,
                "pack": str(pack_root),
                "compatibilityTextureScaleDivisor": TEXTURE_SCALE,
                "hostTexturePolicy": "original Dreamcast dimensions and PNG pixels",
                "mappingCount": len(host_entries),
                "uniqueRuntimeKeyCount": len(host_sources),
                "entries": host_entries,
            },
            indent=2,
        )
        + "\n",
        encoding="utf-8",
    )

    report = {
        "schemaVersion": 1,
        "scope": "SM2 topology-changing Spider-Man costumes with DC counterparts",
        "status": "structural-build-complete; runtime visual review required",
        "hostTexturePack": str(pack_root),
        "hostTextureMappingCount": len(host_entries),
        "hostTextureUniqueKeyCount": len(host_sources),
        "results": results,
    }
    report_path = output / "special-dc-costumes.json"
    report_path.write_text(json.dumps(report, indent=2) + "\n", encoding="utf-8")
    print(f"report: {report_path}")


if __name__ == "__main__":
    main()
